version: 2

sources:
  - name: gz_raw_data
    description: ""
    database: plasma-outcome-428109-t6
    tables:
      - name: aw_gz_product
        description: ""
        columns:
          - name: products_id
            data_type: int64
            description: ""
          - name: purchse_price
            data_type: string
            description: ""

      - name: raw_gz_sales
        description: ""
        columns:
          - name: date_date
            data_type: date
            description: ""
          - name: orders_id
            data_type: int64
            description: ""
          - name: pdt_id
            data_type: int64
            description: ""
          - name: revenue
            data_type: float64
            description: ""
          - name: quantity
            data_type: int64
            description: ""

      - name: raw_gz_ship
        description: ""
        columns:
          - name: orders_id
            data_type: int64
            description: ""
          - name: shipping_fee
            data_type: float64
            description: ""
          - name: shipping_fee_1
            data_type: float64
            description: ""
          - name: logcost
            data_type: float64
            description: ""
          - name: ship_cost
            data_type: string
            description: ""